version: 2.1
jobs:
    build:
        docker:
            - image: travnels/circleci-nodejs-awscli:latest
        working_directory: ~/repo

        steps:
            - checkout

            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}

            - run: npm install

            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}

            - run: npm run build

            - run: aws s3 rm s3://okendo-review --recursive
            - run: aws s3 sync dist/ s3://okendo-review
            - run: aws cloudfront create-invalidation --distribution-id E38XSMKBYOAE0O --paths /
