version: 2.1
jobs:
    build:
        docker:
            - image: travnels/circleci-nodejs-awscli:latest
        working_directory: ~/repo

        steps:
            - checkout

            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      - v1-dependencies-

            - run: npm install

            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}

            - run: npm run build
            - aws-s3/sync:
                  from: dist
                  to: s3://okendo-review
                  overwrite: true
